version: '3.8'

services:
  app:
    build: .
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: vijaysugali98
      DB_NAME: organizationtree
    ports:
      - '3000:3000'
